version: '2'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    links:
      - db
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@db:5432/db'

    volumes:
      - "static-files:/app/staticfiles"
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: db
  nginx:
    restart: always
    image: nginx:1.11.6-alpine
    ports:
      - 80:8000
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app:ro

volumes:
  static-files: